### ISSUE TITLE
Should we implement DBI?

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#1]
This is a database, even if it's not a SQL database.

**Comment by alexkyllo** [comment]
It's a database, but since we're communicating with it over HTTP rather than a pipe, a "connection" is not really a resource that can be "opened"/"closed" and there is no concept of a "transaction" so those parts of the API will be different or non-existent... but otherwise I do think most of the DBI API is applicable, and it'd be better to implement that than our own non-standard API for doing basic database-level queries and operations.

**Comment by Hong-Revo** [comment]
Thinking about it a bit more, this could be tricky because there are different endpoints for queries and commands. With regular SQL you can use dbGetQuery/dbSendQuery for everything.

**Comment by alexkyllo** [comment]
The azure-kusto-python package handles this by simply checking if the query starts with "." and if so, it's a management command. We could do the same.

https://github.com/Azure/azure-kusto-python/blob/5e6c652b1f041b95fa5f8aeb479bbd45db806af1/azure-kusto-data/azure/kusto/data/request.py#L261

**Comment by Hong-Revo** [comment]
Cool, I'll have a stab at it then.

**Comment by Hong-Revo** [comment]
closed by #30
