### ISSUE TITLE
Combine run_query and run_command into 1 function

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/AzureKusto#25]
There's a lot of duplicated functionality in `run_query` and `run_command`. From the implementation perspective, It looks like the only differences are that commands start with a ".", and use a different URI. We could just check the 1st letter of the query string and dispatch to the correct URI.

@alexkyllo what do you think?

**Comment by Hong-Revo** [comment]
Forgot to add: post-processing of returned tables is also different for commands and queries, but again, can just set this based on type of call.

**Comment by alexkyllo** [comment]
Yeah, I agree with dispatching and setting the endpoint suffix to "/query" or "/mgmt" based on whether the query string starts with a '.' character. This is what the Python package does. We can reduce code duplication this way.

Queries accept parameters and commands don't, but we can just ignore the params if it's a command.

**Comment by Hong-Revo** [comment]
I think we can just expose `call_kusto`, since the run_xxx functions were the only layer between it and the user.

**Comment by alexkyllo** [comment]
Since `run_query` is a function that basically everyone using this package is definitely using, a breaking change to that means everyone has to rewrite their scripts if they update the package. 

Also, I don't like the idea of exporting `call_kusto` partly because it includes the internal codename of the product, and the public-facing name could still change. I think `run_query` is still the better name for the user-facing API function.

My suggestion is to either deprecate `run_command` and enhance `run_query` to handle commands, or just keep them both and refactor them to eliminate the code duplication.

**Comment by Hong-Revo** [comment]
Eh, we probably have, like, ten users right now. This package is still in a state of flux, so I'm not worried about breaking changes just yet.

Also, pretty much everything in the package uses the name "Kusto". If that changes, we'll have to change all the names in here as well.

You can have a look at my current refactoring in the ingest branch. Basically I just renamed `run_query` to `call_kusto`, deleted `run_command`, and renamed `call_kusto` to `call_kusto_internal`. I can rename it back to `run_query` though.

**Comment by alexkyllo** [comment]
Yeah, I really think `run_query` is a better name for the main query-running function, can we stick with that name? I like the changes otherwise.

**Comment by Hong-Revo** [comment]
Ok, renamed back.
